### ISSUE TITLE
how to run it on linux without installing cuda?

### ISSUE THREAD

**Issue by zorvalth** [zjazz/zjazz_cuda_miner_experimental#1]
Hi, when i run it on hiveos it says it needs libcudart.so.9.1 or libcudart.so.9.2 , is it possible to run without installing the whole devkit on hiveos?

**Comment by zjazz** [comment]
It seems like it is possible. I never did it but some users already did it. If you have the library installed on the system you will have to set your LD_LIBRARY_PATH to the path where the cuda library folder. Another option is to copy the libcudart.so.9.1/libcudart.so.9.2 library to the miner's folder.
